# Encodings classification 
Here we train simple classifier on encodings obtained via Wavenet autoencoder to recognize speakers

import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="6"

In [1]:
import numpy as np
import tensorflow as tf
from scipy.io import wavfile
from glob import glob

/home/julia/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/home/julia/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
def load_encodings(path):
    data, labels = [], []

    for file in glob("{}/*.npy".format(path)):
        label = file.split('/')[-1].split('-')[0]
        sample = np.load(file)

        data.append(sample[np.newaxis,:,:])
        labels.append(int(label))
        
    return np.array(data), np.array(labels)

def convert_speakers_to_labels(labels, convertion_dict = None):
    return np.array([convertion_dict[l] for l in labels], dtype = np.int32)

In [3]:
def cnn_model_fn(features, labels, mode):
    """Model function for CNN."""
    # Input Layer
    input_layer = tf.reshape(features["x"], [-1, H, W, C])
    
        # Convolutional Layer #1
    conv1 = tf.layers.conv2d(
      inputs=input_layer,
      filters=128,
      kernel_size= [1, 3],
      padding="same",
      activation=tf.nn.relu)
    
            # Convolutional Layer #2
    conv2 = tf.layers.conv2d(
      inputs=conv1,
      filters=128,
      kernel_size= [1, 3],
      padding="same",
      activation=tf.nn.relu)
    
                # Convolutional Layer #3
    conv3 = tf.layers.conv2d(
      inputs=conv2,
      filters=128,
      kernel_size= [1, 3],
      padding="same",
      activation=tf.nn.relu)
    
                    # Convolutional Layer #3
    conv4 = tf.layers.conv2d(
      inputs=conv3,
      filters=128,
      kernel_size= [1, 3],
      padding="same",
      activation=tf.nn.relu)
    
    flat = tf.reshape(conv4, [-1, 1 * W * 128])
    dense = tf.layers.dense(inputs=flat, units=4096, activation=tf.nn.relu)

#     # Convolutional Layer #1
#     conv1 = tf.layers.conv2d(
#       inputs=input_layer,
#       filters=32,
#       kernel_size= [1, 5],
#       padding="same",
#       activation=tf.nn.relu)

#     # Pooling Layer #1
#     pool1 = tf.layers.max_pooling2d(inputs=conv1, pool_size=[1, 2], strides=2)

#     # Convolutional Layer #2 and Pooling Layer #2
#     conv2 = tf.layers.conv2d(
#       inputs=pool1,
#       filters=64,
#       kernel_size= [1, 5],
#       padding="same",
#       activation=tf.nn.relu)
#     pool2 = tf.layers.max_pooling2d(inputs=conv2, pool_size=[1, 2], strides=2)
#     print(pool2.shape)

#     # Dense Layer
#     pool2_flat = tf.reshape(pool2, [-1, 1 * 19 * 64])
#     dense = tf.layers.dense(inputs=pool2_flat, units=1024, activation=tf.nn.relu)
    dropout = tf.layers.dropout(
      inputs=dense, rate=0.4, training=mode == tf.estimator.ModeKeys.TRAIN)

    # Logits Layer
    logits = tf.layers.dense(inputs=dropout, units=NUM_CLASSES)

    predictions = {
      # Generate predictions (for PREDICT and EVAL mode)
      "classes": tf.argmax(input=logits, axis=1),
      # Add `softmax_tensor` to the graph. It is used for PREDICT and by the
      # `logging_hook`.
      "probabilities": tf.nn.softmax(logits, name="softmax_tensor")
    }

    if mode == tf.estimator.ModeKeys.PREDICT:
        return tf.estimator.EstimatorSpec(mode=mode, predictions=predictions)

    # Calculate Loss (for both TRAIN and EVAL modes)
    loss = tf.losses.sparse_softmax_cross_entropy(labels=labels, logits=logits)

    # Configure the Training Op (for TRAIN mode)
    if mode == tf.estimator.ModeKeys.TRAIN:
        optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
        train_op = optimizer.minimize(
            loss=loss,
            global_step=tf.train.get_global_step())
        return tf.estimator.EstimatorSpec(mode=mode, loss=loss, train_op=train_op)

    # Add evaluation metrics (for EVAL mode)
    eval_metric_ops = {
      "accuracy": tf.metrics.accuracy(
          labels=labels, predictions=predictions["classes"])}
    
    return tf.estimator.EstimatorSpec(mode=mode, loss=loss, eval_metric_ops=eval_metric_ops)



In [4]:
train_path = '/home/julia/DeepVoice_data/LibriSpeech_encodings/train/'
val_path = '/home/julia/DeepVoice_data/LibriSpeech_encodings/val/'
test_path = '/home/julia/DeepVoice_data/LibriSpeech_encodings/test/'


train_data, train_labels = load_encodings(train_path)
eval_data, eval_labels = load_encodings(test_path)

In [5]:
print(train_data.shape, train_labels.shape)
print(eval_data.shape, eval_labels.shape)

H, W, C = train_data.shape[1:]
NUM_CLASSES = len(set(train_labels))

(18000, 1, 78, 16) (18000,)
(4680, 1, 78, 16) (4680,)


In [6]:
NUM_CLASSES

40

In [16]:
speaker_to_label = {v:k for k,v in enumerate(set(train_labels))}

train_labels = convert_speakers_to_labels(train_labels, speaker_to_label)
eval_labels = convert_speakers_to_labels(eval_labels, speaker_to_label)

In [20]:
# Create the Estimator
model_dir = "/home/julia/DeepVoice_project/encodings_classifier/"

clsf = tf.estimator.Estimator(model_fn=cnn_model_fn, model_dir=model_dir)

tensors_to_log = {"probabilities": "softmax_tensor"}
logging_hook = tf.train.LoggingTensorHook(tensors=tensors_to_log, every_n_iter=50)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/home/julia/DeepVoice_project/encodings_classifier/', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f603c0d4da0>, '_task_type': 'worker', '_task_id': 0, '_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [21]:
train_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": train_data},
    y=train_labels,
    batch_size=100,
    num_epochs=None,
    shuffle=True)

clsf.train(
    input_fn=train_input_fn,
    steps=20000,
    hooks=[logging_hook])

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /home/julia/DeepVoice_project/encodings_classifier/model.ckpt.
INFO:tensorflow:probabilities = [[0.01688471 0.01758206 0.00938007 ... 0.01417516 0.03091511 0.01640902]
 [0.01203297 0.05408828 0.00765484 ... 0.01415341 0.03369755 0.02480076]
 [0.01571248 0.03525371 0.01087624 ... 0.00970396 0.06888904 0.00276336]
 ...
 [0.17773561 0.00747581 0.00007827 ... 0.00001193 0.5095254  0.00007335]
 [0.01884608 0.03091452 0.01654469 ... 0.00730657 0.03204101 0.00408874]
 [0.01677448 0.04751701 0.01415975 ... 0.0158923  0.05272238 0.00673609]]
INFO:tensorflow:loss = 4.0574274, step = 1
INFO:tensorflow:probabilities = [[0.02043661 0.02060511 0.02712553 ... 0.02501205 0.03615574 0.02433878]
 [0.03197548 0.02191939 0.02934717 ... 0.03059599 0.02041087 0.03092039]
 [0.01375898 0.02132535 0.02951997 ... 0.02413001 0.02875932 0.02804292]
 ...
 [0.0144984  0.0254676  0.01923623 ... 0.00997289 0.02556578 0.01495436]

INFO:tensorflow:loss = 3.567951, step = 701 (93.510 sec)
INFO:tensorflow:probabilities = [[0.01486826 0.02648546 0.03345847 ... 0.02640484 0.02023498 0.01500046]
 [0.02911959 0.02497749 0.0224328  ... 0.02530225 0.02272226 0.0189719 ]
 [0.02398855 0.02353867 0.01921143 ... 0.02623864 0.02516138 0.02036546]
 ...
 [0.02067989 0.03578645 0.02408696 ... 0.01971703 0.01838668 0.01842279]
 [0.0255583  0.01960515 0.02171549 ... 0.03225912 0.01693996 0.02021005]
 [0.02816894 0.02649257 0.02938569 ... 0.01343827 0.02788052 0.02021397]] (46.947 sec)
INFO:tensorflow:global_step/sec: 1.06799
INFO:tensorflow:probabilities = [[0.01690621 0.01478107 0.06105847 ... 0.06249715 0.00817019 0.00744627]
 [0.03412849 0.02475675 0.03313759 ... 0.02781691 0.01671866 0.01390999]
 [0.03106522 0.02658591 0.03148503 ... 0.01934672 0.01871306 0.01512081]
 ...
 [0.03005154 0.02752848 0.0332555  ... 0.02598482 0.01329488 0.01560542]
 [0.02744525 0.00668234 0.02887032 ... 0.05335961 0.01031774 0.0022159 ]
 [0.0198827

INFO:tensorflow:global_step/sec: 1.07889
INFO:tensorflow:probabilities = [[0.03588699 0.02280136 0.02428421 ... 0.0226227  0.03086901 0.01451504]
 [0.01236192 0.02031258 0.02975614 ... 0.00595496 0.03264241 0.00890004]
 [0.01366655 0.01634182 0.01403555 ... 0.00858104 0.03524837 0.00893037]
 ...
 [0.03455123 0.01740283 0.08257198 ... 0.03274385 0.01533079 0.01513522]
 [0.00792564 0.00838646 0.00730834 ... 0.00678718 0.02849814 0.00489734]
 [0.02169133 0.0159704  0.01298547 ... 0.01119975 0.04695765 0.01115951]] (46.374 sec)
INFO:tensorflow:loss = 3.4629376, step = 1501 (92.687 sec)
INFO:tensorflow:probabilities = [[0.04795167 0.01978025 0.04187144 ... 0.03189029 0.01611188 0.03811201]
 [0.02344877 0.01036309 0.03284519 ... 0.02957386 0.01294622 0.00384347]
 [0.02918971 0.01652823 0.03857497 ... 0.0194148  0.02496758 0.01182333]
 ...
 [0.01583905 0.01018049 0.01215775 ... 0.00996368 0.01959323 0.01275854]
 [0.01551135 0.01967809 0.01842128 ... 0.01892376 0.03006244 0.00903155]
 [0.01208

INFO:tensorflow:probabilities = [[0.01981167 0.01303417 0.03554793 ... 0.01083059 0.01853861 0.00822689]
 [0.05140831 0.02452084 0.05737937 ... 0.20853846 0.04404867 0.00081615]
 [0.01939975 0.01415921 0.03224416 ... 0.01855646 0.03232745 0.01513479]
 ...
 [0.0362     0.0219676  0.07222185 ... 0.06087952 0.01251007 0.01631042]
 [0.02231798 0.02805236 0.01683603 ... 0.00915619 0.012029   0.00936723]
 [0.01789914 0.02488833 0.00888232 ... 0.02074851 0.00968476 0.02037096]] (47.144 sec)
INFO:tensorflow:global_step/sec: 1.06441
INFO:tensorflow:probabilities = [[0.0357574  0.02233151 0.04134127 ... 0.02503841 0.02660996 0.00665794]
 [0.00520296 0.01029066 0.06633265 ... 0.00800761 0.02143226 0.0054089 ]
 [0.00176699 0.0055917  0.00330011 ... 0.00228827 0.01513507 0.00089725]
 ...
 [0.0149127  0.01188181 0.02182754 ... 0.01791538 0.01339641 0.005011  ]
 [0.08204373 0.01362202 0.02515091 ... 0.02163769 0.03015037 0.01953322]
 [0.05559342 0.02534188 0.0291194  ... 0.02207431 0.01692718 0.00933

INFO:tensorflow:loss = 2.909392, step = 3001 (95.019 sec)
INFO:tensorflow:probabilities = [[0.00758468 0.04984102 0.01963498 ... 0.00544273 0.01295251 0.01464533]
 [0.00749234 0.01008767 0.02895085 ... 0.005148   0.05088572 0.0096593 ]
 [0.02747678 0.04511909 0.01757231 ... 0.01107744 0.01266827 0.01307244]
 ...
 [0.02046476 0.03173772 0.06552833 ... 0.04097369 0.01351911 0.00577999]
 [0.01200806 0.02762412 0.03478209 ... 0.01578571 0.02254393 0.01076846]
 [0.00293068 0.00566583 0.00469635 ... 0.00670223 0.04265055 0.00204745]] (47.156 sec)
INFO:tensorflow:global_step/sec: 1.06994
INFO:tensorflow:probabilities = [[0.01472092 0.04509114 0.00714645 ... 0.01422815 0.0483887  0.06169147]
 [0.03476437 0.01937305 0.04692582 ... 0.02387048 0.04377238 0.02196108]
 [0.00341075 0.03054372 0.04483506 ... 0.00590769 0.00226128 0.02403251]
 ...
 [0.01267714 0.00580766 0.02765093 ... 0.01171796 0.04997412 0.00221263]
 [0.00591653 0.02887749 0.02554391 ... 0.01068315 0.01439103 0.02321452]
 [0.001438

INFO:tensorflow:global_step/sec: 1.07676
INFO:tensorflow:probabilities = [[0.09679863 0.06017824 0.00824048 ... 0.04628405 0.01187518 0.07927406]
 [0.00301322 0.04953628 0.02569956 ... 0.00806119 0.02071613 0.00164123]
 [0.04149003 0.14370313 0.01406472 ... 0.01707191 0.00121667 0.03185201]
 ...
 [0.03581175 0.09135812 0.05081062 ... 0.03242654 0.01138934 0.05379838]
 [0.01294258 0.01061223 0.01629054 ... 0.0084085  0.01165795 0.00380274]
 [0.00011725 0.00053317 0.00452729 ... 0.00026248 0.05499242 0.00000547]] (46.391 sec)
INFO:tensorflow:loss = 2.4891558, step = 3801 (92.871 sec)
INFO:tensorflow:probabilities = [[0.02271549 0.02365027 0.01180345 ... 0.23278281 0.0015656  0.02328483]
 [0.00249467 0.12075206 0.01873845 ... 0.0315848  0.0002802  0.13573322]
 [0.01165614 0.01495964 0.0269878  ... 0.00645068 0.01520726 0.00082187]
 ...
 [0.00577523 0.01873288 0.04942307 ... 0.07185743 0.00282674 0.010099  ]
 [0.00165219 0.01382599 0.02868679 ... 0.00311854 0.00693923 0.0011143 ]
 [0.00312

INFO:tensorflow:loss = 2.074819, step = 4501 (93.107 sec)
INFO:tensorflow:probabilities = [[0.01993482 0.01769014 0.00629506 ... 0.01675431 0.01604425 0.04324834]
 [0.00263865 0.00295382 0.00767071 ... 0.00163635 0.00892116 0.00912386]
 [0.00114453 0.00933738 0.01666019 ... 0.02157341 0.04121137 0.00372615]
 ...
 [0.000085   0.00060544 0.00033186 ... 0.00006528 0.00015263 0.00000115]
 [0.03514079 0.05926009 0.06152521 ... 0.03511909 0.01376117 0.18112421]
 [0.00021975 0.0002576  0.00232705 ... 0.00007025 0.01177034 0.00000456]] (46.321 sec)
INFO:tensorflow:global_step/sec: 1.06425
INFO:tensorflow:probabilities = [[0.02227105 0.0018087  0.0371784  ... 0.00131577 0.02073079 0.00031487]
 [0.00074825 0.00265079 0.0067075  ... 0.00313692 0.04784846 0.00069642]
 [0.00071947 0.00029566 0.00044428 ... 0.00004905 0.01540087 0.0000438 ]
 ...
 [0.00737821 0.00515176 0.00676044 ... 0.00270018 0.09159561 0.00125863]
 [0.01185795 0.04743439 0.07062061 ... 0.01846392 0.00153111 0.01493123]
 [0.005517

INFO:tensorflow:global_step/sec: 1.06355
INFO:tensorflow:probabilities = [[0.00092881 0.00389442 0.01798437 ... 0.00014642 0.08098631 0.00058886]
 [0.00000369 0.00043422 0.00119643 ... 0.00028132 0.06997045 0.00006113]
 [0.00084631 0.0031076  0.00182668 ... 0.05764832 0.00039149 0.00016147]
 ...
 [0.00476759 0.00351689 0.02615232 ... 0.00436491 0.03576164 0.00272101]
 [0.05880908 0.00810957 0.00446014 ... 0.1095854  0.00541328 0.03792251]
 [0.00000017 0.00000171 0.00000402 ... 0.00000021 0.00138151 0.00000437]] (47.187 sec)
INFO:tensorflow:loss = 1.3047366, step = 5301 (94.026 sec)
INFO:tensorflow:probabilities = [[0.00328805 0.01758953 0.03184949 ... 0.00216639 0.00068608 0.00238251]
 [0.13102044 0.0126408  0.02557094 ... 0.08082263 0.0086104  0.00286584]
 [0.00025916 0.00076988 0.00008102 ... 0.00093925 0.00000362 0.00013347]
 ...
 [0.00495553 0.02058104 0.00864427 ... 0.01054642 0.00240528 0.00533379]
 [0.00034253 0.00641791 0.00658105 ... 0.00013144 0.00046209 0.00005682]
 [0.01729

INFO:tensorflow:probabilities = [[0.01818755 0.00188206 0.00170906 ... 0.00326267 0.0056959  0.06698709]
 [0.03314959 0.0012579  0.00119464 ... 0.00014745 0.00092544 0.00048673]
 [0.00042593 0.0000401  0.01735202 ... 0.00035035 0.00015124 0.00002926]
 ...
 [0.01032388 0.01799966 0.0652495  ... 0.00136665 0.00227237 0.10265896]
 [0.00382133 0.00085948 0.00811379 ... 0.00509783 0.0001815  0.0000926 ]
 [0.08576899 0.13277087 0.00268185 ... 0.03437544 0.00417967 0.00733133]] (47.365 sec)
INFO:tensorflow:global_step/sec: 1.05957
INFO:tensorflow:probabilities = [[0.00692571 0.00079114 0.00271103 ... 0.196248   0.00005042 0.05837753]
 [0.01074515 0.00000644 0.00039585 ... 0.9113962  0.00002376 0.0000215 ]
 [0.34645864 0.06305128 0.00500672 ... 0.02718715 0.00044449 0.00078603]
 ...
 [0.00085212 0.00002322 0.00757542 ... 0.00281776 0.00799986 0.00005389]
 [0.0082613  0.02493738 0.03441389 ... 0.00887343 0.00013411 0.05243395]
 [0.00001768 0.00601168 0.00791002 ... 0.0004291  0.00030481 0.00003

INFO:tensorflow:loss = 0.57150584, step = 6801 (93.526 sec)
INFO:tensorflow:probabilities = [[0.01478246 0.95159954 0.00002784 ... 0.00434734 0.00001008 0.00003443]
 [0.00038124 0.00205943 0.00242041 ... 0.00428758 0.01419931 0.00002955]
 [0.00104281 0.00219534 0.00796362 ... 0.20814611 0.00010322 0.00557782]
 ...
 [0.00002456 0.00000247 0.00000764 ... 0.00738815 0.00342023 0.00003036]
 [0.00001474 0.00100519 0.0002303  ... 0.00102432 0.00205673 0.00000224]
 [0.00004394 0.00000075 0.00000044 ... 0.00003584 0.00000018 0.00017922]] (47.560 sec)
INFO:tensorflow:global_step/sec: 1.06276
INFO:tensorflow:probabilities = [[0.00108893 0.00017239 0.00042552 ... 0.00052173 0.00000312 0.00000205]
 [0.00043368 0.0000922  0.00028736 ... 0.00269713 0.00047489 0.00002002]
 [0.00001756 0.00000203 0.00000137 ... 0.00000045 0.00324454 0.00002555]
 ...
 [0.01860361 0.15130235 0.03501106 ... 0.14835498 0.00004982 0.00133587]
 [0.01328348 0.00043926 0.00046985 ... 0.0129667  0.00000071 0.00064675]
 [0.0180

INFO:tensorflow:global_step/sec: 1.02205
INFO:tensorflow:probabilities = [[0.00002646 0.00000169 0.00000132 ... 0.00006499 0.00070283 0.00000018]
 [0.00002581 0.00000721 0.00010835 ... 0.00000242 0.00588149 0.0000138 ]
 [0.00000199 0.00000001 0.         ... 0.         0.00000003 0.        ]
 ...
 [0.00000641 0.00000364 0.9537011  ... 0.00000043 0.00038334 0.0000006 ]
 [0.00019807 0.00002372 0.00247972 ... 0.00002915 0.00000391 0.00004246]
 [0.00000523 0.00011418 0.00000009 ... 0.00008569 0.         0.00000762]] (48.692 sec)
INFO:tensorflow:loss = 0.18820629, step = 7601 (97.843 sec)
INFO:tensorflow:probabilities = [[0.00045958 0.00043488 0.00038593 ... 0.00225225 0.00008728 0.00002772]
 [0.00016139 0.01001121 0.00008133 ... 0.01194169 0.00000017 0.0000144 ]
 [0.0001053  0.00004874 0.0113047  ... 0.00000256 0.0000106  0.00000067]
 ...
 [0.         0.         0.         ... 0.         0.00000004 0.        ]
 [0.00133575 0.00001766 0.00178189 ... 0.00003298 0.00022798 0.00009297]
 [0.0000

INFO:tensorflow:loss = 0.15825109, step = 8301 (94.601 sec)
INFO:tensorflow:Saving checkpoints for 8305 into /home/julia/DeepVoice_project/encodings_classifier/model.ckpt.
INFO:tensorflow:probabilities = [[0.00000546 0.00000386 0.00000011 ... 0.00000286 0.00001026 0.00000001]
 [0.00008353 0.00193636 0.00018685 ... 0.00037205 0.00000056 0.00021766]
 [0.0000713  0.00022593 0.00035648 ... 0.0042673  0.00000011 0.00003587]
 ...
 [0.00001612 0.         0.00000382 ... 0.         0.         0.0000454 ]
 [0.0000251  0.00768708 0.01144137 ... 0.00044666 0.00000023 0.00009372]
 [0.00067391 0.00000884 0.0128418  ... 0.00501993 0.00039848 0.00020657]] (47.731 sec)
INFO:tensorflow:global_step/sec: 1.05311
INFO:tensorflow:probabilities = [[0.00000014 0.00000209 0.00000038 ... 0.000005   0.00000077 0.00000006]
 [0.00000036 0.00105605 0.00021786 ... 0.00000049 0.00000025 0.00000001]
 [0.00018472 0.00007358 0.00000069 ... 0.00001837 0.00000536 0.00011609]
 ...
 [0.00007102 0.00000587 0.00014846 ... 0.0

INFO:tensorflow:global_step/sec: 1.02808
INFO:tensorflow:probabilities = [[0.00028118 0.00029589 0.00000419 ... 0.00001373 0.00009865 0.00000095]
 [0.00000019 0.00000316 0.00000003 ... 0.00000034 0.00011084 0.00000065]
 [0.         0.00000013 0.         ... 0.00000003 0.         0.        ]
 ...
 [0.00041852 0.00001508 0.99043626 ... 0.0000158  0.00000101 0.00000291]
 [0.00000012 0.00000002 0.00000263 ... 0.00000053 0.0000232  0.00000001]
 [0.02161288 0.00002398 0.00057568 ... 0.00060196 0.00001325 0.00010844]] (48.886 sec)
INFO:tensorflow:loss = 0.12769395, step = 9101 (97.269 sec)
INFO:tensorflow:probabilities = [[0.00000056 0.00000005 0.00009173 ... 0.00195591 0.00019514 0.00000085]
 [0.00813501 0.00015505 0.01515719 ... 0.00003439 0.7043177  0.00000091]
 [0.00000085 0.         0.         ... 0.         0.         0.        ]
 ...
 [0.00078705 0.00002733 0.00012223 ... 0.0000003  0.00000002 0.00000005]
 [0.02107096 0.00197164 0.00298193 ... 0.00023546 0.00002692 0.0008199 ]
 [0.0000

INFO:tensorflow:loss = 0.0941704, step = 9801 (97.028 sec)
INFO:tensorflow:probabilities = [[0.00000001 0.00000567 0.0000403  ... 0.00000822 0.00052521 0.00000033]
 [0.         0.         0.         ... 0.         0.00016995 0.00000002]
 [0.00000012 0.         0.         ... 0.00005515 0.00000004 0.00000027]
 ...
 [0.00001803 0.01714574 0.00034015 ... 0.00088157 0.0000004  0.00000315]
 [0.00023587 0.00004952 0.00008112 ... 0.00000978 0.0000394  0.00073823]
 [0.         0.0000092  0.00005437 ... 0.0000016  0.         0.99804854]] (48.404 sec)
INFO:tensorflow:global_step/sec: 0.988687
INFO:tensorflow:probabilities = [[0.00111074 0.00918427 0.00442675 ... 0.00619186 0.00034011 0.00138447]
 [0.00006609 0.00084062 0.00005924 ... 0.00259362 0.00254835 0.00000026]
 [0.00000027 0.00022186 0.00005682 ... 0.00001476 0.00000032 0.00189247]
 ...
 [0.00324875 0.00000096 0.00015182 ... 0.00886063 0.00003664 0.00002471]
 [0.00000001 0.00000001 0.00008391 ... 0.         0.         0.00000223]
 [0.0006

INFO:tensorflow:global_step/sec: 0.961875
INFO:tensorflow:probabilities = [[0.00000106 0.0000002  0.0000016  ... 0.00000002 0.02540331 0.00000004]
 [0.00000201 0.00005386 0.00000011 ... 0.00000002 0.00417212 0.00000067]
 [0.0000977  0.00227428 0.00000157 ... 0.9897391  0.00068945 0.00007608]
 ...
 [0.00057855 0.00000273 0.00001319 ... 0.01286553 0.00000007 0.00016777]
 [0.00000066 0.00000083 0.00000094 ... 0.00000579 0.         0.0000039 ]
 [0.         0.00000034 0.00000019 ... 0.00000009 0.         0.00000002]] (55.132 sec)
INFO:tensorflow:loss = 0.08572142, step = 10601 (103.951 sec)
INFO:tensorflow:probabilities = [[0.00000386 0.         0.0000196  ... 0.00141744 0.         0.        ]
 [0.00005483 0.00000614 0.00009626 ... 0.00000224 0.00489179 0.00000001]
 [0.00000174 0.00000021 0.00000705 ... 0.00000026 0.         0.0001796 ]
 ...
 [0.00010337 0.00018351 0.00001105 ... 0.00000474 0.00003893 0.00000334]
 [0.00000407 0.00003293 0.00000032 ... 0.00000302 0.00004117 0.00000969]
 [0.0

INFO:tensorflow:loss = 0.037018746, step = 11301 (107.387 sec)
INFO:tensorflow:Saving checkpoints for 11325 into /home/julia/DeepVoice_project/encodings_classifier/model.ckpt.
INFO:tensorflow:probabilities = [[0.00000037 0.00000005 0.00000003 ... 0.00000253 0.         0.        ]
 [0.00000102 0.         0.00000014 ... 0.         0.         0.        ]
 [0.00000534 0.00004356 0.0000268  ... 0.00000563 0.00000256 0.00000311]
 ...
 [0.00000518 0.00000005 0.         ... 0.00000004 0.99928623 0.00000459]
 [0.         0.00000001 0.         ... 0.         0.         0.        ]
 [0.00000299 0.0002736  0.00000191 ... 0.00106959 0.00000005 0.00368544]] (51.405 sec)
INFO:tensorflow:global_step/sec: 0.970591
INFO:tensorflow:probabilities = [[0.00003258 0.00000001 0.00000188 ... 0.00000038 0.00000693 0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00002579 0.0000067  0.00023878 ... 0.00000001 0.         0.9940375 ]
 ...
 [0.0000001  0.00000039 0.00003129 ..

INFO:tensorflow:global_step/sec: 1.04725
INFO:tensorflow:probabilities = [[0.0000012  0.00004956 0.00000022 ... 0.9991504  0.00000094 0.00004695]
 [0.00018138 0.00045805 0.00221853 ... 0.00003482 0.00000017 0.00000039]
 [0.00000358 0.00152621 0.00003551 ... 0.00029014 0.00000354 0.00003877]
 ...
 [0.         0.00000103 0.00002496 ... 0.         0.         0.        ]
 [0.0000001  0.00000004 0.00000081 ... 0.0000001  0.00000186 0.        ]
 [0.00000269 0.00005796 0.78656477 ... 0.00389253 0.00000007 0.00066291]] (47.519 sec)
INFO:tensorflow:loss = 0.020871172, step = 12101 (95.497 sec)
INFO:tensorflow:probabilities = [[0.00002521 0.00000064 0.0000001  ... 0.00000157 0.00009197 0.00000002]
 [0.0000021  0.00000003 0.00018806 ... 0.         0.0000007  0.00000001]
 [0.00000052 0.00005505 0.00047155 ... 0.00000314 0.00000027 0.00000058]
 ...
 [0.00423894 0.00000009 0.00009274 ... 0.00135438 0.00015001 0.0000295 ]
 [0.00000027 0.00000701 0.00002059 ... 0.00004538 0.00030383 0.00000106]
 [0.00

INFO:tensorflow:loss = 0.075953916, step = 12801 (96.735 sec)
INFO:tensorflow:probabilities = [[0.00000005 0.         0.00000001 ... 0.         0.00000004 0.        ]
 [0.00000002 0.         0.         ... 0.         0.0000005  0.00000003]
 [0.00001784 0.00000083 0.00000016 ... 0.         0.         0.00000025]
 ...
 [0.00000037 0.00009088 0.00000328 ... 0.         0.00614877 0.00000002]
 [0.00000585 0.00000004 0.00004482 ... 0.00000008 0.00000004 0.00025682]
 [0.         0.         0.9999887  ... 0.         0.         0.        ]] (55.936 sec)
INFO:tensorflow:global_step/sec: 0.933702
INFO:tensorflow:probabilities = [[0.00000005 0.00000009 0.         ... 0.         0.         0.        ]
 [0.00000496 0.00001322 0.9997663  ... 0.00000081 0.00005169 0.00000025]
 [0.00000012 0.00000464 0.0000009  ... 0.00000002 0.         0.00000007]
 ...
 [0.00000076 0.00000026 0.00000025 ... 0.00157312 0.         0.00015203]
 [0.00040306 0.00003111 0.00020983 ... 0.9903778  0.00000074 0.00038123]
 [0. 

INFO:tensorflow:global_step/sec: 0.948211
INFO:tensorflow:probabilities = [[0.9902063  0.003983   0.00257894 ... 0.0000028  0.00000486 0.00003507]
 [0.         0.00000043 0.9697935  ... 0.00000002 0.         0.00000211]
 [0.00000003 0.00000137 0.00018725 ... 0.00000042 0.         0.00001712]
 ...
 [0.00000026 0.00240534 0.00000048 ... 0.00000489 0.00000687 0.        ]
 [0.00000012 0.00000416 0.00000665 ... 0.09473117 0.00368062 0.00000066]
 [0.00070596 0.00006574 0.00117636 ... 0.00065865 0.00007779 0.00001437]] (50.379 sec)
INFO:tensorflow:loss = 0.032930244, step = 13601 (105.461 sec)
INFO:tensorflow:probabilities = [[0.         0.00000611 0.00000023 ... 0.00000151 0.00000613 0.00000005]
 [0.0000004  0.0000014  0.0004437  ... 0.00000005 0.00000001 0.        ]
 [0.00000001 0.         0.00000002 ... 0.         0.99998844 0.        ]
 ...
 [0.00000065 0.00004965 0.00001714 ... 0.0000095  0.00000001 0.        ]
 [0.00031424 0.00003302 0.000225   ... 0.00002836 0.00000002 0.00000009]
 [0.

INFO:tensorflow:loss = 0.018287571, step = 14301 (100.728 sec)
INFO:tensorflow:probabilities = [[0.00000004 0.00000004 0.00000017 ... 0.00000313 0.00000084 0.00000012]
 [0.00000001 0.         0.00000054 ... 0.0000014  0.00000649 0.        ]
 [0.         0.00000477 0.00000002 ... 0.00000001 0.         0.00000001]
 ...
 [0.         0.00000532 0.00000004 ... 0.00002397 0.00000003 0.        ]
 [0.00000098 0.00000085 0.00918048 ... 0.00000426 0.00000009 0.06147544]
 [0.00000064 0.00004483 0.00001879 ... 0.00246101 0.         0.00000008]] (56.057 sec)
INFO:tensorflow:global_step/sec: 0.946932
INFO:tensorflow:probabilities = [[0.00000295 0.00000031 0.         ... 0.00000435 0.00000001 0.00000024]
 [0.00000055 0.00001138 0.00031508 ... 0.00045484 0.00000489 0.00000005]
 [0.         0.         0.         ... 0.         0.00000115 0.        ]
 ...
 [0.00000015 0.04126286 0.00000018 ... 0.00001227 0.00000016 0.00000001]
 [0.00000801 0.         0.00000135 ... 0.         0.0000196  0.        ]
 [0.

INFO:tensorflow:global_step/sec: 1.10046
INFO:tensorflow:probabilities = [[0.00000001 0.00000409 0.         ... 0.         0.00000001 0.00000005]
 [0.00000514 0.00007074 0.00056076 ... 0.00000047 0.00018917 0.0000095 ]
 [0.00000419 0.00070034 0.00000032 ... 0.00070669 0.         0.00003569]
 ...
 [0.00013248 0.00000025 0.00000004 ... 0.00036771 0.         0.00008139]
 [0.00000011 0.         0.00000884 ... 0.00000027 0.00000573 0.        ]
 [0.00000001 0.         0.00000064 ... 0.00000003 0.00000001 0.        ]] (45.732 sec)
INFO:tensorflow:loss = 0.0046587274, step = 15101 (90.870 sec)
INFO:tensorflow:probabilities = [[0.00000001 0.00000027 0.9997125  ... 0.00000005 0.00000002 0.        ]
 [0.00004021 0.00000039 0.00001744 ... 0.00006763 0.00000637 0.00000547]
 [0.         0.00000019 0.00000007 ... 0.         0.         0.        ]
 ...
 [0.00001553 0.00000126 0.00000004 ... 0.00000125 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.00000003]
 [0.0

INFO:tensorflow:loss = 0.0079764975, step = 15801 (122.681 sec)
INFO:tensorflow:probabilities = [[0.00616734 0.00000774 0.00000293 ... 0.00000472 0.0000001  0.00000072]
 [0.00000476 0.00015742 0.00005659 ... 0.99908304 0.00000051 0.00000002]
 [0.         0.00000079 0.00000596 ... 0.00000077 0.00000014 0.00000001]
 ...
 [0.00000242 0.00000382 0.00000014 ... 0.00000001 0.         0.        ]
 [0.         0.         0.9998652  ... 0.         0.00000001 0.00000016]
 [0.00000001 0.000003   0.00012097 ... 0.00000257 0.         0.        ]] (65.092 sec)
INFO:tensorflow:Saving checkpoints for 15864 into /home/julia/DeepVoice_project/encodings_classifier/model.ckpt.
INFO:tensorflow:global_step/sec: 0.774914
INFO:tensorflow:probabilities = [[0.         0.00000055 0.         ... 0.         0.         0.        ]
 [0.00000114 0.00081127 0.0000266  ... 0.00000002 0.00029961 0.00013115]
 [0.00000784 0.00116326 0.00002684 ... 0.993008   0.00000009 0.00000022]
 ...
 [0.00000002 0.00000829 0.00000012 .

INFO:tensorflow:global_step/sec: 0.850484
INFO:tensorflow:probabilities = [[0.0000002  0.00000902 0.00000063 ... 0.         0.         0.        ]
 [0.         0.00000011 0.00000002 ... 0.00000221 0.         0.        ]
 [0.00000011 0.11677954 0.00000001 ... 0.         0.00000003 0.        ]
 ...
 [0.00000051 0.02223236 0.00000002 ... 0.00215642 0.         0.00000109]
 [0.00000103 0.00000099 0.00001743 ... 0.00000135 0.00176932 0.00004293]
 [0.         0.         0.         ... 0.         0.         0.        ]] (59.661 sec)
INFO:tensorflow:loss = 0.019879892, step = 16601 (117.579 sec)
INFO:tensorflow:probabilities = [[0.         0.00009209 0.0007975  ... 0.         0.00000005 0.        ]
 [0.000321   0.0360843  0.9473654  ... 0.00000215 0.00000002 0.00000011]
 [0.00000003 0.00000432 0.00000122 ... 0.00000028 0.00000495 0.00000541]
 ...
 [0.00029579 0.00041114 0.00002095 ... 0.00000057 0.00000042 0.00012406]
 [0.00000002 0.00000001 0.         ... 0.         0.         0.00000003]
 [0.

INFO:tensorflow:loss = 0.00971849, step = 17301 (106.956 sec)
INFO:tensorflow:Saving checkpoints for 17346 into /home/julia/DeepVoice_project/encodings_classifier/model.ckpt.
INFO:tensorflow:probabilities = [[0.00000001 0.00000059 0.         ... 0.00000608 0.         0.        ]
 [0.00000094 0.         0.00000514 ... 0.00000005 0.         0.00001583]
 [0.0000002  0.00000224 0.00000005 ... 0.00000035 0.         0.00000013]
 ...
 [0.0000018  0.94508153 0.00000005 ... 0.00327887 0.00067014 0.        ]
 [0.         0.         0.00000153 ... 0.00000078 0.00015859 0.00000001]
 [0.         0.         0.         ... 0.         0.00000323 0.        ]] (61.422 sec)
INFO:tensorflow:global_step/sec: 0.857833
INFO:tensorflow:probabilities = [[0.00000019 0.         0.00000001 ... 0.9999988  0.         0.00000001]
 [0.         0.00000003 0.         ... 0.         0.         0.00000018]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.9999604  ...

INFO:tensorflow:global_step/sec: 1.01073
INFO:tensorflow:probabilities = [[0.         0.         0.         ... 0.00000002 0.         0.        ]
 [0.00001263 0.00025581 0.00005852 ... 0.00000003 0.00000008 0.00035785]
 [0.00000059 0.00000131 0.00000002 ... 0.00000049 0.00000587 0.00000012]
 ...
 [0.00000166 0.00000001 0.         ... 0.00000178 0.         0.00000001]
 [0.         0.00000001 0.00000125 ... 0.00000139 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]] (50.750 sec)
INFO:tensorflow:loss = 0.0030122194, step = 18101 (98.939 sec)
INFO:tensorflow:probabilities = [[0.00000083 0.0000814  0.00000003 ... 0.0000003  0.0000193  0.00000045]
 [0.00000076 0.00010433 0.00032023 ... 0.00000292 0.00005564 0.0000003 ]
 [0.00000001 0.         0.00000004 ... 0.         0.00000339 0.00000003]
 ...
 [0.         0.00001081 0.00000004 ... 0.00000122 0.         0.00000035]
 [0.00000042 0.00001026 0.00002068 ... 0.0000022  0.00000004 0.00000018]
 [0. 

INFO:tensorflow:loss = 0.0044044806, step = 18801 (96.068 sec)
INFO:tensorflow:probabilities = [[0.0006974  0.00000075 0.00001828 ... 0.00036057 0.00000004 0.00001429]
 [0.         0.         0.         ... 0.         0.00004554 0.        ]
 [0.00029344 0.00007418 0.9986821  ... 0.00068252 0.00000011 0.00000044]
 ...
 [0.00000204 0.00000313 0.         ... 0.         0.00000026 0.        ]
 [0.         0.00000053 0.00000106 ... 0.         0.00000243 0.        ]
 [0.0003161  0.         0.00000039 ... 0.00000026 0.00000012 0.        ]] (55.837 sec)
INFO:tensorflow:global_step/sec: 0.962861
INFO:tensorflow:probabilities = [[0.0000384  0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.00000002 ... 0.00000002 0.         0.        ]
 [0.9941744  0.0000172  0.0000001  ... 0.0000589  0.00000171 0.0000045 ]
 ...
 [0.00008494 0.         0.00000001 ... 0.00001015 0.00000006 0.00000308]
 [0.         0.00000061 0.         ... 0.         0.         0.        ]
 [0.

KeyboardInterrupt: 

In [22]:
# Evaluate the model and print results
eval_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": eval_data},
    y=eval_labels,
    num_epochs=1,
    shuffle=False)

eval_results = clsf.evaluate(input_fn=eval_input_fn)
print(eval_results)


INFO:tensorflow:Starting evaluation at 2018-05-10-18:56:15
INFO:tensorflow:Restoring parameters from /home/julia/DeepVoice_project/encodings_classifier/model.ckpt-18532
INFO:tensorflow:Finished evaluation at 2018-05-10-18:56:29
INFO:tensorflow:Saving dict for global step 18532: accuracy = 0.17478633, global_step = 18532, loss = 5.70595
{'accuracy': 0.17478633, 'loss': 5.70595, 'global_step': 18532}
